
toolkit:
  env:
    - name: CONTAINERD_CONFIG
      value: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml"
    - name: CONTAINERD_SOCKET
      value: "/run/k3s/containerd/containerd.sock"
    - name: CONTAINERD_RUNTIME_CLASS
      value: "nvidia"
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"

# devicePlugin:
#   config:
#     create: true
#     name: mps-slicing-config-all
#     data:
#       any: |-
#         version: v1
#         flags:
#           migStrategy: none
#         sharing:
#           mps:
#             resources:
#             - name: nvidia.com/gpu
#               replicas: 4

dcgmExporter:
  enabled: true
  env:
    - name: DCGM_EXPORTER_INTERVAL
      value: "1000"
  config:
    create: true
    name: custom-dcgm-exporter-metrics
    data:
      dcgm-metrics.csv: |-
        # If line starts with a '#' it is considered a comment
        # DCGM FIELD, Prometheus metric type, help message
        # DCGM_FI_DEV_SM_CLOCK, gauge, SM clock frequency (in MHz).
        # DCGM_FI_DEV_MEM_CLOCK, gauge, Memory clock frequency (in MHz).
        DCGM_FI_DEV_GPU_UTIL, gauge, GPU utilization (in %).
        DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).
        # DCGM_FI_DEV_FB_FREE, gauge, Framebuffer memory free (in MiB).
        # DCGM_FI_DEV_FB_USED, gauge, Framebuffer memory used (in MiB).
        # DCGM_FI_PROF_GR_ENGINE_ACTIVE, gauge, Ratio of time the graphics engine is active.
