apiVersion: apps/v1
kind: Deployment
metadata:
  name: coqui-deployment
  labels:
    app: coqui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coqui
  template:
    metadata:
      labels:
        app: coqui
    spec:
      runtimeClassName: nvidia
      containers:
      - name: coqui
        image: nvantu/drafas-coqui:latest
        imagePullPolicy: IfNotPresent
        command: ['python3', 'TTS/server/server.py', '--model_name', 'tts_models/en/vctk/vits', '--use_cuda', 'true']
        ports:
        - containerPort: 5002
        resources:
          limits:
            nvidia.com/gpu: 1  # Uncomment if GPU is needed; requires GPU nodes
            cpu: 3
            # memory: "4Gi"
          requests:
            nvidia.com/gpu: 1
            cpu: 2
            # memory: "4Gi"
        startupProbe:
          httpGet:
            path: /
            port: 5002
          failureThreshold: 60
          periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: coqui-service
spec:
  selector:
    app: coqui
  ports:
  - name: http
    protocol: TCP
    port: 5002
    targetPort: 5002
    nodePort: 30502
  type: LoadBalancer
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-ratelimit-coqui
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: coqui
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|5002"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 7
                  tokens_per_fill: 7
                  fill_interval: 2s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'
