apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-deployment
  labels:
    app: pytorch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      runtimeClassName: nvidia
      containers:
      - name: pytorch
        # image: pytorch/pytorch:2.5.0-cuda11.8-cudnn9-runtime
        image: nvantu/drafas-pytorch
        imagePullPolicy: IfNotPresent
        command: ['python', 'server.py']
        # command: ['sleep', '1000000']
        ports:
        - containerPort: 8005
        resources:
          limits:
            nvidia.com/gpu: 1  # Use 1 GPU, remove this line if using CPU-only
            cpu: 3
          requests:
            nvidia.com/gpu: 1
            cpu: 2

        startupProbe:
          httpGet:
            path: /ready
            port: 8005
          # exec:
          #   command:
          #   - curl
          #   - localhost:8005/ready
          failureThreshold: 60
          periodSeconds: 2
---
---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-service
spec:
  selector:
    app: pytorch
  ports:
  - name: http
    protocol: TCP
    port: 8005  # Expose http port
    targetPort: 8005
    nodePort: 30805
  type: LoadBalancer  # Change to NodePort if not using a cloud provider with LoadBalancer support

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-ratelimit-pytorch
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: pytorch
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8005"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 14
                  tokens_per_fill: 14
                  fill_interval: 1s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'

