apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  labels:
    app: ollama
spec:
  replicas: 1  # Number of replicas for load balancing
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      runtimeClassName: nvidia
      containers:
      - name: ollama-server
        image: nvantu/drafas-ollama:latest
        ports:
        - containerPort: 11434  # Port where Ollama listens for requests
        resources:
          limits:
            nvidia.com/gpu: 1  # Use 1 GPU, remove this line if using CPU-only
          requests:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
  - name: http
    protocol: TCP
    port: 11434          # External port
    targetPort: 11434  # The port on the Ollama container
  type: LoadBalancer  # Use NodePort if not on a cloud provider
