apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper-deployment
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      runtimeClassName: nvidia
      containers:
      - name: whisper-container
        image: onerahmet/openai-whisper-asr-webservice:latest-gpu
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          limits:
            nvidia.com/gpu: 1  # Uncomment if GPU is needed; requires GPU nodes
          requests:
            nvidia.com/gpu: 1
        env:
        - name: ASR_MODEL
          value: "base"  # Choose the Whisper model size (tiny, base, small, medium, large)
        - name: ASR_ENGINE
          value: "faster_whisper"  # Default port for the API server
---
apiVersion: v1
kind: Service
metadata:
  name: whisper-service
spec:
  selector:
    app: whisper
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30900
  type: LoadBalancer
