name: "resnet50"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "data"
    data_type: TYPE_FP32
    dims: [3, 224, 224]
  }
]

output [
  {
    name: "resnetv24_dense0_fwd"
    data_type: TYPE_FP32
    dims: [1000]
    label_filename: "labels.txt"
  }
]

